global:
  config:
    value: global
service:
  config:
    p2: value-global
logging:
  file: /app/distribute/logs/${spring.application.name}/${spring.application.name}.log
management:
  security:
      enabled: false
  context-path: /manage

security:
  user:
    name: user
    password: pass

eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    metadata-map:
            management:
              context-path: ${management.context-path}
            user.name: ${security.user.name}
            user.password: ${security.user.password}