global:
  config:
    value: global
service:
  config:
    p2: value-global
logging:
  file: /app/distribute/logs/${spring.application.name}/${spring.application.name}.log
management:
  security:
      enabled: false
  context-path: /manage